### ISSUE TITLE
CSVs with invalid rows should fail on upload

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#102]
This resulted from a conversation in this PR: https://github.com/rubyforgood/abalone/pull/88

Currently, when a CSV is processed with some invalid rows, we reject the invalid rows and save the valid rows. However, we should not save _any_ rows to the db because this risks the user of duplicating data. Let's reject the entire CSV and tell the user to fix the invalid rows and re-upload the file.

**Comment by wesleyeewong** [comment]
I'd like to tackle this, but will wait till this PR is merged: https://github.com/rubyforgood/abalone/pull/103

Since it's refactoring the importing flow.

A couple of ideas to do this:
1) Use ActiveRecord::Rollback on the transaction
2) Create each row using `.new` and validate it using `.valid?`. This would potentially have us look at all the rows first before actually saving anything, and storing the unsaved objects in memory.

I'm leaning towards option # 1. Let me know if there're better ways of doing this :)

**Comment by rafaltrojanowski** [comment]
Sorry, for jumping at the last moment. It seems like an interesting problem. I'm thinking that maybe we could serialize ActiveRecord errors in another column and store it. thanks to that we could easily display validation errors. the tricky part is how to prevent duplicates? maybe by introducing a scope? Just a rough idea. later we could also clean up those invalid records periodically. to be able to save those invalid records we would have to use `save(validate: false)`. For errors `hstore` suits perfectly. From my experience it's better to have a track of all operations in the database, it's easier to track down the issues potentially.

**Comment by wesleyeewong** [comment]
@rafaltrojanowski  ah interesting, didn't know we have that feature. Unfortunately, I think it's broken. As I recall from the refactor due to DigitalOcean? Heroku? not being able to write files out, and we had to store the csv in memory.

My current solution will record all invalid rows and show it as stats on the main uploaded files page.

@corneliusellen maybe we should have a ticket for that broken feature.
