### ISSUE TITLE
Rename 'master' branch to 'primary' or 'production'

### ISSUE THREAD

**Issue by jtu0** [rubyforgood/abalone#161]

**Comment by jtu0** [comment]
@mdworken

**Comment by mdworken** [comment]
Hey @jtu0 , interesting suggestion! I take it this is an inclusivity recommendation? If so, I like it!!

I'm a little on the fence about the cost/benefit here though, because I really want to make the project as beginner-friendly as possible and am worried it might cause confusion/frustration. BUT I also think it's otherwise the absolute right thing to do, and I'm having trouble deciding how to feel.

I'll message you on this in slack - I wonder that if we do it we should make it an org-wide decision, and that way we can add a disclaimer/explanation to it across all the different projects? If it becomes our (Ruby for Good's) "thing" I think it would improve the inclusivity benefits AND reduce confusion when people jump from project to project!

**Comment by mdworken** [comment]
Closing for now in response to the GH news - we'll hopefully be able to do this ruby for good -wide now!
