### ISSUE TITLE
Background image in hero is not decorative, needs text

### ISSUE THREAD

**Issue by NiquiCara** [rubyforgood/abalone#532]
The hero image is set in a background, which is ok, but there is no text for it. 

We need to have "Abalone Analytics" included as a heading element within that container. Adding the `.sr-only` class should make it invisible except to screen readers.

![hero-image-background](https://user-images.githubusercontent.com/45127691/102560633-b32dcb80-40a0-11eb-81ff-22ea2b55a95c.PNG)

**Comment by metamoni** [comment]
Hi,

We already have an H1 in the navigation and that says 'Abalone Analytics'. If we add a sr-only heading here, a screen reader user will actually hear 'Abalone Analytics' read out to them _twice_ as heading level 1.

I think there are a few things to think about here. Do we want multiple H1s on a page (there's a long debate about whether this is the right thing to do or not)? If we do, this is fine as it is and we can count this background as 'decorative'.

If we only want one H1 per page, do we always want that to be 'Abalone Analytics'? If yes, then we can change all other page titles to H2 to improve the page structure. If no, then we need to update the navigation to change this to a regular link instead of an <h1> and the rest of the pages can stay as they are, as they seem to use the page title as <h1> already (although I haven't checked _all_ of them).

**Comment by CraigJZ** [comment]
Hi @metamoni. Thank you for looking into this. My preference, especially since most of our pages don't have a lot of content, would be to have a single `<h1>` tag on each. I think we would want to change the Abalone Analytics `<h1>` to be a regular link and leave the rest of the pages as they are, using the page title as the `<h1>`. I am happy to move that work into a separate issue. 

If we do that, I _think_ this issue would then stay as it is, with Abalone Analytics as the `<h1>` on the home page. What do you think?

**Comment by metamoni** [comment]
Yes, you're right. We'd need to have a hidden 'Abalone Analytics' as the h1 here then. I'll go ahead and add it in.

It'd be great if you could open a new issue for the points discussed above. I'd be happy to pick that up.
