### ISSUE TITLE
Testing - Write Feature/Integration Tests for UntaggedAnimalAssessmentJob

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#67]
BLOCKED: `UntaggedAnimalAssessmentJob` must be created first.

Tests need to be written for `UntaggedAnimalAssessmentJob`.

Please use a fixture file for testing in this directory: `db/sample_data_files/untagged_animal_assessment/`

**Feature/Integration Tests**
The following contexts and expected outcomes should be tested:
1. Context: The user uploads a CSV that has already been processed.
Outcome: 
- A new `ProcessedFile` record should be created 
- On the /file_uploads page, the user should see:
  - File has Status: "Failed"
  - File has Errors: "Already processed a file with the same name. Data not imported!"
  - File has Statistics: "{}"

2. Context: The user uploads a CSV with invalid headers.
Outcome:
- A new `ProcessedFile` record should be created 
- On the /file_uploads page, the user should see:
  - File has Status: "Failed"
  - File has Errors: "Does not have valid headers. Data not imported!"
  - File has Statistics: "{}"

3. Context: The user successfully uploads a CSV with no errors:
Outcome:
- A new `ProcessedFile` record should be created 
- 201 new `UntaggedAnimalAssessment` records should be created
- On the /file_uploads page, the user should see:
  - File has Status: "Processed"
  - File has no Errors
  - File has Statistics: "{row_count: 201, rows_imported: 201, rows_not_imported: 0, shl_case_numbers: {"SF16-9A": 100, "SF16-9B": 20, "SF16-9C": 10, "SF16-9D": 71}}"

4. Context: The user successfully uploads a CSV with errors for 2 rows:
Outcome:
- A new `ProcessedFile` record should be created 
- 199 new `UntaggedAnimalAssessment` records should be created
- On the /file_uploads page, the user should see:
  - File has Status: "Processed"
  - File has Errors: "Does not have valid headers. Data not imported!"
  - File has Statistics: "{row_count: 201, rows_imported: 199, rows_not_imported: 2, shl_case_numbers: {"SF16-9A": 100, "SF16-9B": 20, "SF16-9C": 10, "SF16-9D": 69}}"

**Comment by rafaltrojanowski** [comment]
I have started working on this. Before I will invest more time, I like to confirm that files in the `untagged_animal_assessment` dir are in the correct format (and encoding). I've noticed leading comma that I had to remove from CSV file, and headers are slightly different ie:

```
"Length" vs "Length (mm)
"Mass" vs "Mass (g)
```

This is not a big deal.

**I'm experiencing an issue with encoding**, here are more details:
https://gist.github.com/rafaltrojanowski/9714e7bafebc87f4590cef747b788f44

I'm concerned about this because tagged_animal_assesment files seem to be working fine. Maybe they were generated in different environments. I guess we need to support this weird encoding as well.

For now, I don't have an idea of how to solve these issues with different bytes (see my gist).

**Comment by rafaltrojanowski** [comment]
It may be a solution to remove a BOM character on the beginning of the file:

https://github.com/ruby/csv/issues/43

**Comment by rafaltrojanowski** [comment]
Problem with  BOM character already solved.

**Comment by corneliusellen** [comment]
@rafaltrojanowski Seems like you've figure it out, but yes for clarification the CSV files in the `sample_data_files` directory may or may not need some cleaning up. These are just raw sample files we've received from the lab.

**Comment by rafaltrojanowski** [comment]
I see. I saw that they include a row index. I will clean them up to be consistent with code. Later, if there is a need to handle this format, we could add an Index in headers.
